// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/ashiqsabith123/user-details-svc/pkg/config"
	"github.com/ashiqsabith123/user-details-svc/pkg/db"
	"github.com/ashiqsabith123/user-details-svc/pkg/repository"
	"github.com/ashiqsabith123/user-details-svc/pkg/service"
	"github.com/ashiqsabith123/user-details-svc/pkg/usecase"
	"github.com/ashiqsabith123/user-details-svc/pkg/utils"
)

// Injectors from wire.go:

func IntializeService(config2 config.Config) service.UserService {
	gormDB := db.ConnectToDatabase(config2)
	userRepo := repository.NewUserRepo(gormDB)
	utilsUtils := utils.NewS3Client(config2)
	userUsecase := usecase.NewUserUsecase(userRepo, utilsUtils)
	userService := service.NewUserService(userUsecase)
	return userService
}
